### ISSUE TITLE
Sensor updates

### ISSUE THREAD

**Issue by AlanSmithe** [jrhubott/homebridge-homeseer#5]
Hi I was wondering if you could look into to following problem;

Whenever a sensor is triggered the Homekit app only updates the value the first time. If I leave homekit open and running the sensor doesn't get updates anymore. When I close the app and reopen it again then the value gets updated.

All the switches and lightbulbs do get updated.
This is also visible in the logs because every device and value is visible in the logs and only the sensors are missing.

`Nov 16 15:32:27 HomeBridge homebridge[2530]: [2017-11-16 15:32:27] [HomeSeer] Pioneer: Periodic status update rate=60 seconds

Nov 16 15:32:27 HomeBridge homebridge[2530]: [2017-11-16 15:32:27] [HomeSeer] Pioneer: getPowerState function succeeded: value=0

Nov 16 15:32:28 HomeBridge homebridge[2530]: [2017-11-16 15:32:28] [HomeSeer] Doorbell: Periodic status update rate=60 seconds

Nov 16 15:32:31 HomeBridge homebridge[2530]: [2017-11-16 15:32:31] [HomeSeer] Bathroom: Periodic status update rate=60 seconds

Nov 16 15:32:31 HomeBridge homebridge[2530]: [2017-11-16 15:32:31] [HomeSeer] Bathroom: getPowerState function succeeded: value=0`

**Comment by tomdrumdrum** [comment]
Same issue!

**Comment by AlanSmithe** [comment]
Workaround with another plugin 'homebridge-http-motion-sensor'.
Let HomeSeer run a script when motion is detected and use something like this
hs.URLAction("http://IP:PORT/", "GET", "", "")
